{% set name = "django-photologue" %}
{% set version = "3.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: af49cdaa7b428b7cb53e1fa06e66d788866512737ca56e98634be3ef24cdefb4

build:
  number: 0
  noarh: pytthon
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - django-sortedm2m >=3.1.1
    - exifread >=2.1.2
    - pillow >=10.0.0
    - pip
    - python >=3.8
  run:
    - django-sortedm2m >=3.1.1
    - exifread >=2.1.2
    - pillow >=10.0.0
    - python >=3.8

about:
  home: "https://github.com/richardbarran/django-photologue"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Powerful image management for the Django web framework."
  doc_url: https://django-photologue.readthedocs.io/en/stable/
  dev_url: https://github.com/richardbarran/django-photologue

extra:
  recipe-maintainers:
    - https://github.com/gb119
